name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      tag_name:
        tag_name:
        description: 'Tag name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: chekout tag
      uses: actions/checkout@v2
      with: 
        ref: refs/tags/${{ github.event.inputs.tag_name }}
    
    - name: delete source code files
      run: ls -la
      
    - run: echo "Hello ${{ github.event.inputs.tag_name }}!"
