name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      tag_name:
        tag_name:
        description: 'Tag name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello ${{ github.event.inputs.tag_name }}!"
