name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: chekout tag
      uses: actions/checkout@v2
      with: refs/tags/${{ github.event.inputs.tag_name }}
    
    - name: delete source code files
      run: ls -la
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Deploy to Google Cloud
    - name: execute deploy command
