on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - uses: actions/checkout@v2
