name: Test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Parse node version
        run: |
          echo "NODE_VERSION=$(cat package.json | grep '@types/node' | grep -Po '\d+.\d+.\d+')" >> $GITHUB_ENV
          echo $NODE_VERSION

      - name: Node $NODE_VERSION
        uses: actions/setup-node@v1
        with:
          node-version: $NODE_VERSION

      - name: npm install and npm run test
        run: |
          npm ci
          npm run test
